import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "./components/navbar";
import Sidebar from "./components/sidebar";
// import VendorManagement from "./components/VendorMangement";
import BrandVerification from "./components/BrandVerification";
import AddProduct from "./components/AddProduct";
import RFQReceived from "./components/RFQRecieved";
import WebsiteData from "./components/WebsiteData";
import AppData from "./components/AppData";
import Queries from "./components/Queries";
import VerifiedBrands from "./components/VerifiedBrands";
import ProductList from "./components/ProductList";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Admin Portal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <div className="flex w-full">
          <Sidebar />
          <main className="w-full">
            {children}
            {/* <VendorManagement /> */}
            {/* <BrandVerification /> */}
            {/* <ProductList /> */}
            {/* <AddProduct /> */}

            {/* For Web  */}
            {/* <WebsiteData /> */}
            {/* <RFQReceived /> */}


            {/* For App */}
            {/* <AppData /> */}
            {/* <Queries /> */}

            {/* <VerifiedBrands /> */}
          </main>
        </div>
      </body>
    </html>
  );
}