import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "./components/navbar";
import Sidebar from "./components/sidebar";
// import SamplesHome from "@/samples/samplesHome";
// import OrderTrackingStepsHome from "./components/OderTrackingStepsHome";
// import VendorManagement from "./components/VendorMangement";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Admin Portal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <div className="flex w-full">
          <Sidebar />
          <main className="w-full">
            {children}
            {/* <VendorManagement /> */}
            {/* <OrderTrackingStepsHome /> */}
          </main>
        </div>
      </body>
    </html>
  );
}