import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "../app/components/navbar";
import Sidebar from "./components/sidebar";
import VendorManagement from "./components/VendorMangement";
import BrandVerification from "./components/BrandVerification";
import AddProduct from "./components/AddProduct";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Admin Portal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

<Navbar />
<Sidebar />
<VendorManagement />
<BrandVerification />
<AddProduct />        
        {children}
      </body>
    </html>
  );
}
